# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather' do
  use_frameworks!
  
  pod 'PopupController'
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 3.4'

  target 'WeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
